'use client';
import { useEffect, useMemo, useState } from 'react';
import { Bell, CalendarDays, ChevronRight, CircleCheck, Clock3, LayoutDashboard, Menu, MessageCircle, MoreHorizontal, Plus, Search, Users, X } from 'lucide-react';

type Lead = { initials:string; name:string; service:string; channel:string; status:string; task:string; due:string; urgency:'late'|'today'|'scheduled'; note:string };
const leads: Lead[] = [
  { initials:'NS', name:'นลินี ศรีสุข', service:'เลเซอร์กำจัดขน', channel:'Facebook', status:'ติดต่อแล้ว', task:'โทรติดตามผลครั้งที่ 2', due:'เกินกำหนด 35 นาที', urgency:'late', note:'ลูกค้าขอให้ติดต่อช่วงพักกลางวัน' },
  { initials:'PK', name:'พิมพ์ชนก กิตติ', service:'โปรแกรมผิวหน้า', channel:'LINE', status:'กำลังติดตาม', task:'ส่งข้อความติดตามผล', due:'วันนี้ ก่อน 13:00', urgency:'today', note:'ส่งเคส Bright Skin และถามเวลาที่สะดวกเข้าพบแพทย์' },
  { initials:'TW', name:'ธนวัฒน์ วงศ์ดี', service:'ฉีดโบท็อกซ์', channel:'Website', status:'ยืนยันนัด', task:'ยืนยันนัดหมาย', due:'วันนี้ 16:00', urgency:'scheduled', note:'นัด 16:30 น. สาขาสุขุมวิท' },
  { initials:'AP', name:'อรพรรณ พูลผล', service:'ฟิลเลอร์', channel:'LINE', status:'กำลังติดตาม', task:'ติดตามหลังส่งโปรโมชัน', due:'วันนี้ ก่อน 17:00', urgency:'today', note:'สนใจจองภายในเดือนนี้' },
  { initials:'KS', name:'กฤษณะ สุขใจ', service:'ยกกระชับ HIFU', channel:'โทรศัพท์', status:'ลีดใหม่', task:'ติดต่อครั้งแรก', due:'พรุ่งนี้ ก่อน 10:00', urgency:'scheduled', note:'สอบถามราคาและระยะพักฟื้น' },
];
const nav = [{ label:'ลีดของฉัน', icon:Users },{ label:'นัดหมายวันนี้', icon:CalendarDays },{ label:'รายชื่อลีด', icon:Search },{ label:'ภาพรวม', icon:LayoutDashboard }];

export default function Home() {
 const [selected,setSelected]=useState(leads[1]); const [completed,setCompleted]=useState<string[]>([]); const [mobileNav,setMobileNav]=useState(false); const [filter,setFilter]=useState<'all'|'late'|'today'>('all');
 const visible=useMemo(()=>leads.filter(l=>filter==='all'||l.urgency===filter),[filter]); const done=completed.includes(selected.name);
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool) return;
  const lifecycle=new AbortController();
  const schema={type:'object',properties:{name:{type:'string'}},required:['name'],additionalProperties:false};
  const find=(input:unknown)=>{const name=(input as {name?:string})?.name; const lead=leads.find(item=>item.name===name); if(!lead) throw new Error('ไม่พบลีด'); return lead};
  void Promise.resolve(context.registerTool({name:'read_lead_next_action',title:'ดูงานถัดไปของลีด',description:'ดูงานและกำหนดเวลาถัดไปของลีดรายหนึ่ง',inputSchema:schema,annotations:{readOnlyHint:true},execute:(input:unknown)=>{const lead=find(input); return {name:lead.name,nextAction:lead.task,due:lead.due,status:lead.status}}},{signal:lifecycle.signal}));
  void Promise.resolve(context.registerTool({name:'select_lead',title:'เปิดรายละเอียดลีด',description:'เลือกลีดเพื่อแสดงรายละเอียดและงานถัดไปในหน้าจอ',inputSchema:schema,execute:(input:unknown)=>{const lead=find(input); setSelected(lead); return {name:lead.name,selected:true}}},{signal:lifecycle.signal}));
  void Promise.resolve(context.registerTool({name:'complete_next_action',title:'บันทึกว่างานเสร็จแล้ว',description:'ทำเครื่องหมายว่างานถัดไปของลีดเสร็จสิ้นใน mockup',inputSchema:schema,execute:(input:unknown)=>{const lead=find(input); setSelected(lead); setCompleted(items=>[...new Set([...items,lead.name])]); return {name:lead.name,completed:true}}},{signal:lifecycle.signal}));
  return()=>lifecycle.abort();
 },[]);
 return <main className="min-h-screen bg-[#f4f7f5] text-[#19312c]">
  <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#dbe5df] bg-white/95 px-4 backdrop-blur md:px-7"><div className="flex items-center gap-3"><button onClick={()=>setMobileNav(true)} className="rounded-lg p-2 md:hidden" aria-label="เปิดเมนู"><Menu size={20}/></button><span className="grid size-9 place-items-center rounded-xl bg-[#197365] text-white"><CircleCheck size={19}/></span><span className="font-semibold tracking-tight">Vela Clinic</span></div><div className="flex items-center gap-3 text-sm text-[#61746c]"><span className="hidden sm:block">10 ก.ย. 2026</span><button className="rounded-lg p-2" aria-label="การแจ้งเตือน"><Bell size={19}/></button><span className="grid size-8 place-items-center rounded-full bg-[#e2eeea] text-xs font-semibold text-[#197365]">MY</span></div></header>
  <div className="mx-auto flex max-w-[1440px]">
   <aside className="sticky top-16 hidden h-[calc(100vh-64px)] w-60 shrink-0 border-r border-[#dbe5df] bg-[#f8faf8] p-4 md:block"><p className="px-3 pb-2 pt-2 text-[11px] font-semibold uppercase tracking-[.12em] text-[#789087]">พื้นที่ทำงาน</p>{nav.map(({label,icon:Icon},i)=><button key={label} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${i===0?'bg-[#e5f3ef] font-semibold text-[#17695d]':'text-[#52665e] hover:bg-[#edf2ef]'}`}><Icon size={18}/>{label}</button>)}<div className="px-3 pt-14 text-xs leading-relaxed text-[#71847b]">ทุกลีดควรมี<br/>ผู้รับผิดชอบ และงานถัดไป</div></aside>
   {mobileNav&&<div className="fixed inset-0 z-50 bg-[#19312c]/20 md:hidden"><aside className="h-full w-72 bg-[#f8faf8] p-4 shadow-xl"><div className="mb-6 flex items-center justify-between"><b>เมนู</b><button onClick={()=>setMobileNav(false)} className="rounded-lg p-2"><X size={20}/></button></div>{nav.map(({label,icon:Icon},i)=><button key={label} onClick={()=>setMobileNav(false)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${i===0?'bg-[#e5f3ef] font-semibold text-[#17695d]':'text-[#52665e]'}`}><Icon size={18}/>{label}</button>)}</aside></div>}
   <section className="min-w-0 flex-1 p-5 lg:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-[#197365]">ลีดของฉัน</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">งานที่ต้องทำวันนี้</h1><p className="mt-1 text-sm text-[#61746c]">เรียงตามความเร่งด่วน เพื่อไม่ให้พลาดโอกาสนัดหมาย</p></div><button className="flex items-center gap-2 rounded-xl bg-[#197365] px-4 py-2.5 text-sm font-semibold text-white shadow-sm"><Plus size={17}/>เพิ่มลีด</button></div>
    <div className="mt-6 grid grid-cols-3 gap-3"><Metric label="ต้องติดต่อวันนี้" value="12"/><Metric label="เกินกำหนด" value="3" alert/><Metric label="นัดหมายวันนี้" value="7"/></div>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-3"><h2 className="text-base font-semibold">ลำดับงานที่ควรทำ</h2><div className="flex rounded-xl bg-[#eaf0ed] p-1 text-xs font-medium"><Filter label="ทั้งหมด" active={filter==='all'} onClick={()=>setFilter('all')}/><Filter label="เกินกำหนด" active={filter==='late'} onClick={()=>setFilter('late')}/><Filter label="วันนี้" active={filter==='today'} onClick={()=>setFilter('today')}/></div></div>
    <div className="mt-3 overflow-hidden rounded-2xl border border-[#dce6e0] bg-white">{visible.map(lead=><button key={lead.name} onClick={()=>setSelected(lead)} className={`grid w-full grid-cols-[40px_minmax(0,1fr)_auto] items-center gap-3 border-b border-[#e8eeea] px-4 py-4 text-left last:border-0 hover:bg-[#f7fbf9] sm:grid-cols-[40px_minmax(0,1.2fr)_minmax(120px,.8fr)_minmax(140px,.8fr)_20px] ${selected.name===lead.name?'bg-[#f3faf7]':''}`}><span className="grid size-10 place-items-center rounded-full bg-[#e5f3ef] text-xs font-semibold text-[#197365]">{lead.initials}</span><span><b className="block text-sm font-semibold">{lead.name}</b><span className="mt-1 block text-xs text-[#687b73]">{lead.service} · {lead.channel}</span></span><span className={`hidden rounded-full px-2.5 py-1 text-xs font-semibold sm:block ${lead.urgency==='late'?'bg-[#fbe8e8] text-[#ad4750]':lead.urgency==='today'?'bg-[#fff2db] text-[#9a641b]':'bg-[#e5f3ef] text-[#197365]'}`}>{lead.urgency==='late'?'เกินกำหนด':lead.status}</span><span className="hidden text-xs sm:block"><b className="block font-semibold text-[#344a42]">{lead.task}</b><span className="mt-1 block text-[#70817a]">{lead.due}</span></span><ChevronRight className="text-[#94a69e]" size={18}/></button>)}</div></section>
   <aside className="hidden w-[350px] shrink-0 border-l border-[#dbe5df] bg-white p-6 xl:block"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[#73877e]">รายละเอียดลีด</p><div className="mt-4 flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-[#e5f3ef] text-sm font-semibold text-[#197365]">{selected.initials}</span><div><h2 className="font-semibold">{selected.name}</h2><p className="mt-0.5 text-xs text-[#687b73]">{selected.service} · {selected.channel}</p></div><button className="ml-auto text-[#7e9088]" aria-label="เมนูเพิ่มเติม"><MoreHorizontal size={20}/></button></div><div className="mt-7 rounded-2xl border border-[#cfe5dc] bg-[#f5fbf8] p-4"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#fff2db] text-[#9a641b]"><MessageCircle size={18}/></span><div><p className="text-sm font-semibold">สิ่งที่ต้องทำครั้งถัดไป</p><p className="mt-1 text-xs text-[#9a641b]"><Clock3 className="mr-1 inline" size={13}/>{done?'งานนี้เสร็จแล้ว':selected.due}</p></div></div><p className="mt-4 text-sm leading-6 text-[#40574e]">{done?'ตั้งงานใหม่เพื่อให้การติดตามต่อเนื่อง':selected.note}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div><p className="text-[#758980]">ผู้รับผิดชอบ</p><b className="mt-1 block">เมย์ · สุขุมวิท</b></div><div><p className="text-[#758980]">ช่องทาง</p><b className="mt-1 block">{selected.channel}</b></div></div><div className="mt-5 flex gap-2"><button className="rounded-lg border border-[#cbd9d2] px-3 py-2 text-xs font-semibold">เลื่อนเวลา</button><button onClick={()=>setCompleted(items=>[...new Set([...items,selected.name])])} className="flex-1 rounded-lg bg-[#197365] px-3 py-2 text-xs font-semibold text-white">{done?'ตั้งงานถัดไป':'ทำงานนี้เสร็จแล้ว'}</button></div></div><div className="mt-7"><h3 className="text-sm font-semibold">การติดต่อก่อนหน้า</h3><div className="mt-3 space-y-4 border-l border-[#dce6e0] pl-4 text-xs"><p><b className="block">ตอบกลับครั้งล่าสุด</b><span className="text-[#74867e]">เมื่อวาน 16:42 · ขอรายละเอียดเพิ่ม</span></p><p><b className="block">สร้างลีดจาก {selected.channel}</b><span className="text-[#74867e]">9 ก.ย. 2026 · แคมเปญ Bright Skin</span></p></div></div></aside>
  </div></main>;
}
function Metric({label,value,alert=false}:{label:string;value:string;alert?:boolean}){return <div className="rounded-2xl border border-[#dce6e0] bg-white p-4"><p className="text-xs text-[#6b7f76]">{label}</p><p className={`mt-2 text-2xl font-semibold tracking-tight ${alert?'text-[#b44b54]':''}`}>{value}</p></div>}
function Filter({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`rounded-lg px-3 py-1.5 ${active?'bg-white text-[#17695d] shadow-sm':'text-[#6a7d75]'}`}>{label}</button>}
