import type { CalendarItem, GoogleCalendarConnection } from './types';

export const mockGoogleCalendarConnection: GoogleCalendarConnection = {
  provider: 'google_calendar',
  selectedCalendarName: 'Care D Clinic Operations',
  status: 'connected',
  syncMode: 'automatic',
  lastSyncedAt: '11 ก.ย. 2026 09:55',
};

export const mockCalendarItems: CalendarItem[] = [
  {
    id: 'appointment-24082',
    type: 'appointment',
    title: 'สมฤดี มณี · ประเมินหลอดเลือด',
    date: '2026-08-05',
    startsAt: '09:30',
    endsAt: '10:00',
    owner: 'พยาบาลณิชา',
    linkedLeadId: 'CD-24082',
    syncState: 'synced',
  },
  {
    id: 'task-24091-day1',
    type: 'follow_up_task',
    title: 'โทรติดตาม นลินี ศรีสุข · Day 1',
    date: '2026-08-22',
    startsAt: '10:00',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24091',
    syncState: 'synced',
  },
  {
    id: 'appointment-24095',
    type: 'appointment',
    title: 'กฤษณะ สุขใจ · พบศัลยแพทย์',
    date: '2026-08-27',
    startsAt: '14:00',
    endsAt: '14:30',
    owner: 'พยาบาลณิชา',
    linkedLeadId: 'CD-24095',
    syncState: 'synced',
  },
  {
    id: 'task-24082-day30',
    type: 'follow_up_task',
    title: 'สรุปรอบติดตาม สมฤดี มณี · Day 30',
    date: '2026-09-02',
    startsAt: '10:30',
    owner: 'มุก',
    linkedLeadId: 'CD-24082',
    syncState: 'synced',
  },
  {
    id: 'appointment-24092',
    type: 'appointment',
    title: 'พิมพ์ชนก กิตติ · ประเมินเส้นเลือด',
    date: '2026-09-05',
    startsAt: '13:30',
    endsAt: '14:00',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24092',
    syncState: 'synced',
  },
  {
    id: 'task-24094-first',
    type: 'follow_up_task',
    title: 'ติดตามอาการ อรพรรณ พูลผล · Day 1',
    date: '2026-09-09',
    startsAt: '15:30',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24094',
    syncState: 'synced',
  },
  {
    id: 'task-24091',
    type: 'follow_up_task',
    title: 'ติดตามแผล นลินี ศรีสุข · Day 3',
    date: '2026-09-11',
    startsAt: '11:00',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24091',
    syncState: 'synced',
  },
  {
    id: 'appointment-24093',
    type: 'appointment',
    title: 'ธนวัฒน์ วงศ์ดี · ประเมินเส้นฟอกไต',
    date: '2026-09-11',
    startsAt: '16:30',
    endsAt: '17:00',
    owner: 'พยาบาลณิชา',
    linkedLeadId: 'CD-24093',
    syncState: 'synced',
  },
  {
    id: 'task-24094',
    type: 'follow_up_task',
    title: 'โทรกลับ อรพรรณ พูลผล',
    date: '2026-09-11',
    startsAt: '17:00',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24094',
    syncState: 'pending',
  },
  {
    id: 'appointment-24091-review',
    type: 'appointment',
    title: 'นลินี ศรีสุข · ตรวจแผลหลังหัตถการ',
    date: '2026-09-15',
    startsAt: '09:00',
    endsAt: '09:30',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24091',
    syncState: 'pending',
  },
  {
    id: 'task-24093-day7',
    type: 'follow_up_task',
    title: 'โทรติดตาม ธนวัฒน์ วงศ์ดี · Day 7',
    date: '2026-09-20',
    startsAt: '11:30',
    owner: 'พยาบาลณิชา',
    linkedLeadId: 'CD-24093',
    syncState: 'pending',
  },
  {
    id: 'appointment-24094',
    type: 'appointment',
    title: 'อรพรรณ พูลผล · เปลี่ยนสายฟอกไต',
    date: '2026-09-25',
    startsAt: '16:00',
    endsAt: '16:45',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24094',
    syncState: 'pending',
  },
  {
    id: 'task-24095-prep',
    type: 'follow_up_task',
    title: 'ยืนยันการเตรียมตัว กฤษณะ สุขใจ',
    date: '2026-09-30',
    startsAt: '10:00',
    owner: 'มุก',
    linkedLeadId: 'CD-24095',
    syncState: 'pending',
  },
  {
    id: 'appointment-24093-oct',
    type: 'appointment',
    title: 'ธนวัฒน์ วงศ์ดี · ติดตามผลการรักษา',
    date: '2026-10-03',
    startsAt: '13:00',
    endsAt: '13:30',
    owner: 'พยาบาลณิชา',
    linkedLeadId: 'CD-24093',
    syncState: 'pending',
  },
  {
    id: 'task-24092-oct',
    type: 'follow_up_task',
    title: 'โทรยืนยันนัด พิมพ์ชนก กิตติ',
    date: '2026-10-08',
    startsAt: '10:30',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24092',
    syncState: 'pending',
  },
  {
    id: 'appointment-24095-oct',
    type: 'appointment',
    title: 'กฤษณะ สุขใจ · หัตถการ One Day Surgery',
    date: '2026-10-15',
    startsAt: '08:30',
    endsAt: '09:30',
    owner: 'พยาบาลณิชา',
    linkedLeadId: 'CD-24095',
    syncState: 'pending',
  },
  {
    id: 'task-24091-oct',
    type: 'follow_up_task',
    title: 'ติดตามแผล นลินี ศรีสุข · Day 30',
    date: '2026-10-20',
    startsAt: '11:00',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24091',
    syncState: 'pending',
  },
  {
    id: 'appointment-24092-nov',
    type: 'appointment',
    title: 'พิมพ์ชนก กิตติ · อ่านผลประเมิน',
    date: '2026-11-04',
    startsAt: '15:00',
    endsAt: '15:30',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24092',
    syncState: 'pending',
  },
  {
    id: 'task-24094-nov',
    type: 'follow_up_task',
    title: 'ติดตามหลังเปลี่ยนสาย อรพรรณ พูลผล',
    date: '2026-11-11',
    startsAt: '10:00',
    owner: 'พยาบาลวิภา',
    linkedLeadId: 'CD-24094',
    syncState: 'pending',
  },
  {
    id: 'appointment-24093-nov',
    type: 'appointment',
    title: 'ธนวัฒน์ วงศ์ดี · ประเมินซ้ำ',
    date: '2026-11-25',
    startsAt: '14:30',
    endsAt: '15:00',
    owner: 'พยาบาลณิชา',
    linkedLeadId: 'CD-24093',
    syncState: 'pending',
  },
  {
    id: 'task-24095-dec',
    type: 'follow_up_task',
    title: 'ติดตามอาการ กฤษณะ สุขใจ · Day 30',
    date: '2026-12-05',
    startsAt: '09:30',
    owner: 'พยาบาลณิชา',
    linkedLeadId: 'CD-24095',
    syncState: 'pending',
  },
];
