import type { LeadCase } from './types';

/** Temporary client-side repository. Its interface mirrors the future service boundary. */
export const seedLeadCases: LeadCase[] = [
  {
    id: 'CD-24091',
    initials: 'NS',
    name: 'นลินี ศรีสุข',
    hn: 'HN-104829',
    phone: '081-555-0192',
    service: 'ผ่าตัดสร้างเส้นฟอกไต (AVF)',
    source: 'Facebook',
    status: 'Follow-up active',
    priority: 'High',
    nurse: 'พยาบาลวิภา',
    owner: 'มุก',
    task: 'Day 3 · โทรติดตามแผลหลังผ่าตัด',
    due: 'เกินกำหนด 35 นาที',
    dueState: 'overdue',
    note: 'ผู้ป่วยขอให้ติดต่อช่วงพักฟอกไต',
    plan: 'AVF one-day surgery follow-up v1',
    anchor: '8 ก.ย. 2026',
  },
  {
    id: 'CD-24092',
    initials: 'PK',
    name: 'พิมพ์ชนก กิตติ',
    phone: '089-444-8821',
    service: 'ประเมินหลอดเลือดฟอกไต',
    source: 'LINE OA',
    status: 'Awaiting nurse call',
    priority: 'Normal',
    nurse: 'พยาบาลวิภา',
    owner: 'มายด์',
    task: 'โทรคัดกรองก่อนประเมินเส้นเลือด',
    due: 'วันนี้ ก่อน 13:00',
    dueState: 'today',
    note: 'สอบถามวันฟอกไตและเวลาที่สะดวก',
    plan: 'Vascular access assessment v1',
    anchor: '10 ก.ย. 2026',
  },
  {
    id: 'CD-24093',
    initials: 'TW',
    name: 'ธนวัฒน์ วงศ์ดี',
    hn: 'HN-104611',
    phone: '092-773-2210',
    service: 'แก้ไขเส้นฟอกไตตีบหรืออุดตัน',
    source: 'TikTok',
    status: 'Appointment scheduled',
    priority: 'Normal',
    nurse: 'พยาบาลณิชา',
    owner: 'มุก',
    task: 'Day 1 · ติดตามหลังหัตถการ',
    due: 'พรุ่งนี้ 10:00',
    dueState: 'upcoming',
    note: 'นัดประเมินการไหลเวียน 16:30 น.',
    plan: 'Access intervention follow-up v1',
    anchor: '10 ก.ย. 2026',
  },
  {
    id: 'CD-24094',
    initials: 'AP',
    name: 'อรพรรณ พูลผล',
    phone: '081-555-0192',
    service: 'ใส่หรือดูแลสายฟอกไต',
    source: 'Phone',
    status: 'Contact in progress',
    priority: 'Urgent',
    nurse: 'พยาบาลวิภา',
    owner: 'มายด์',
    task: 'Retry · โทรกลับ',
    due: 'วันนี้ ก่อน 17:00',
    dueState: 'today',
    note: 'ไม่รับสายครั้งก่อน — ขอให้โทรกลับหลัง 17:00',
    plan: 'Dialysis catheter follow-up v1',
    anchor: '9 ก.ย. 2026',
  },
  {
    id: 'CD-24095',
    initials: 'KS',
    name: 'กฤษณะ สุขใจ',
    phone: '086-222-1605',
    service: 'ผ่าตัดหลอดเลือดแบบ One Day Surgery',
    source: 'Other',
    status: 'New',
    priority: 'Low',
    nurse: 'ยังไม่กำหนด',
    owner: 'มุก',
    task: 'มอบหมายพยาบาล',
    due: 'พรุ่งนี้ ก่อน 10:00',
    dueState: 'upcoming',
    note: 'สอบถามการเตรียมตัวก่อนผ่าตัดและผู้ดูแลหลังกลับบ้าน',
    plan: 'ยังไม่ได้เลือก',
    anchor: '—',
  },
  {
    id: 'CD-24082',
    initials: 'SM',
    name: 'สมฤดี มณี',
    hn: 'HN-104205',
    phone: '095-780-1188',
    service: 'ประเมินหลอดเลือดฟอกไต',
    source: 'Facebook',
    status: 'Closed - converted',
    priority: 'Normal',
    nurse: 'พยาบาลณิชา',
    owner: 'มุก',
    task: 'ปิดรอบติดตามแล้ว',
    due: 'ปิดเมื่อ 4 ก.ย.',
    dueState: 'upcoming',
    note: 'เข้ารับการประเมินตามนัดแล้ว',
    plan: 'Vascular access assessment v1',
    anchor: '5 ส.ค. 2026',
    closed: true,
  },
];
