import type { LeadCase } from './types';

/** Temporary client-side repository. Its interface mirrors the future service boundary. */
export const seedLeadCases: LeadCase[] = [
  {
    id: 'CL-24091',
    initials: 'NS',
    name: 'นลินี ศรีสุข',
    hn: 'HN-104829',
    phone: '081-555-0192',
    service: 'เลเซอร์กำจัดขน',
    source: 'Facebook',
    status: 'Follow-up active',
    priority: 'High',
    nurse: 'พญ.กานต์',
    owner: 'มุก',
    task: 'Day 3 · โทรติดตามผล',
    due: 'เกินกำหนด 35 นาที',
    dueState: 'overdue',
    note: 'ลูกค้าขอให้ติดต่อช่วงพักกลางวัน',
    plan: 'Standard v1',
    anchor: '8 ก.ย. 2026',
  },
  {
    id: 'CL-24092',
    initials: 'PK',
    name: 'พิมพ์ชนก กิตติ',
    phone: '089-444-8821',
    service: 'โปรแกรมผิวหน้า',
    source: 'LINE OA',
    status: 'Awaiting nurse call',
    priority: 'Normal',
    nurse: 'พญ.กานต์',
    owner: 'มายด์',
    task: 'โทรประเมินเบื้องต้น',
    due: 'วันนี้ ก่อน 13:00',
    dueState: 'today',
    note: 'ส่งเคส Bright Skin และถามเวลาที่สะดวก',
    plan: 'Standard v1',
    anchor: '10 ก.ย. 2026',
  },
  {
    id: 'CL-24093',
    initials: 'TW',
    name: 'ธนวัฒน์ วงศ์ดี',
    hn: 'HN-104611',
    phone: '092-773-2210',
    service: 'ฉีดโบท็อกซ์',
    source: 'TikTok',
    status: 'Appointment scheduled',
    priority: 'Normal',
    nurse: 'พญ.ภูมิ',
    owner: 'มุก',
    task: 'Day 1 · ยืนยันหลังรับบริการ',
    due: 'พรุ่งนี้ 10:00',
    dueState: 'upcoming',
    note: 'นัด 16:30 น. สาขาสุขุมวิท',
    plan: 'Standard v1',
    anchor: '10 ก.ย. 2026',
  },
  {
    id: 'CL-24094',
    initials: 'AP',
    name: 'อรพรรณ พูลผล',
    phone: '081-555-0192',
    service: 'ฟิลเลอร์',
    source: 'Phone',
    status: 'Contact in progress',
    priority: 'Urgent',
    nurse: 'พญ.กานต์',
    owner: 'มายด์',
    task: 'Retry · โทรกลับ',
    due: 'วันนี้ ก่อน 17:00',
    dueState: 'today',
    note: 'ไม่รับสายครั้งก่อน — ขอให้โทรกลับหลัง 17:00',
    plan: 'Standard v1',
    anchor: '9 ก.ย. 2026',
  },
  {
    id: 'CL-24095',
    initials: 'KS',
    name: 'กฤษณะ สุขใจ',
    phone: '086-222-1605',
    service: 'ยกกระชับ HIFU',
    source: 'Other',
    status: 'New',
    priority: 'Low',
    nurse: 'ยังไม่กำหนด',
    owner: 'มุก',
    task: 'มอบหมายพยาบาล',
    due: 'พรุ่งนี้ ก่อน 10:00',
    dueState: 'upcoming',
    note: 'สอบถามราคาและระยะพักฟื้น',
    plan: 'ยังไม่ได้เลือก',
    anchor: '—',
  },
  {
    id: 'CL-24082',
    initials: 'SM',
    name: 'สมฤดี มณี',
    hn: 'HN-104205',
    phone: '095-780-1188',
    service: 'ปรึกษาผิวหน้า',
    source: 'Facebook',
    status: 'Closed - converted',
    priority: 'Normal',
    nurse: 'พญ.ภูมิ',
    owner: 'มุก',
    task: 'ปิดรอบติดตามแล้ว',
    due: 'ปิดเมื่อ 4 ก.ย.',
    dueState: 'upcoming',
    note: 'เข้ารับบริการแล้ว',
    plan: 'Standard v1',
    anchor: '5 ส.ค. 2026',
    closed: true,
  },
];
